[package]
name = "chromosome"
description = "genetic algorithms tools library"
license= "Apache-2.0"
version = "0.0.6"
authors = ["borys <burbokop@gmail.com>"]
edition = "2021"


[dependencies]
rand = "0.8.5"
