[package]
name = "chromosome"
description = "genetic algorithms tools library"
license= "Apache-2.0"
version = "0.0.8"
authors = ["borys <burbokop@gmail.com>"]
edition = "2021"

[features]
default = [ "std" ]
std = [ "rand/std", "rand/std_rng" ]

[dependencies.rand]
version = "0.8.5"
default-features = false
features = [ "alloc" ]
